#!/usr/bin/env bash
# Configures HAProxy as a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend iykemiracle.tech
    bind *:80
    default_backend web_server

backend web_server
    balance roundrobin
    server 450095-web-01 3.84.168.223:80
    server 450095-web-02 100.26.57.196:80
EOF

sudo service haproxy restart

sudo systemctl enable haproxy
