#!/usr/bin/env bash
# Write a Bash script that displays a list of currently running processes.
# Requirements:
# Must show all processes, for all users, including those which might not have a TTY
ps -auxf